sudo: required
services:
  - docker

before_install:
  - docker build -t kvjnf/docker-react -f Dockerfile.dev .

script:
  - docker run kvjnf/docker-react npm run test -- --coverage

# notifications:
#   email: false
#   slack:
#     secure: secure: "LGVZJX7CJlGUT5tXxcklxwVz0B9IuMqJTPnvBrsZWnYYhIe5OXNX93Z9qq/9pPd5JqGHgKXOytZ2iQrrcUkhxvYoWWzrjBaDqAhKXZTXOPDBnz4ASodt5ZIQUBHKXILqWnFDME/U0uVdqsGmRZ46qKnR75PIytKLfqabHcMzWqIK5BatKfDb8aa6uRGEkMjgr3SU4gDzOmt3S8D2p1+lbmjHMeU7Pq2Uh8awZzsQCV+ws0FB1RRFdFSb9Zq6ApTcQZ8Jw9yTRVE1Td1WChKZGo9MvU+bNXq7i00LxQDChYugpBVCEf8gYDERkTN4INP3tvV9WZzxDT+Zy+z9lf7qeDGeBjogPSVfaK2fm7rZRZBgho2LKF5DJQh5VgAaJdCT9obJWy8s9uE3iVbOmUXN9HYVfT39UBw2PiLshwJhu7bgCUNayyqjtVVFXodg7d4q02kgiIo2Mb4Ys//XRnrBrUbKibhDSTIMJmYVbsI4o7RRdmmFuHOvM2M12BwxLxhKoIqQQpii8FQ2sv+TvDxgz7YTtPD492JRkKKnbzFWCIthvOrXayEvZRb/ZuKf2fTju29kltKJYgeg2eYrCqYhrxCyQsM/F4PsHppCIPMCgIPPNaZjrKPuijqk3/uuQ89r95XXEeYEvt6rMS6Am/Poo6O3zuTn+jGMr0Ca/P9vrNk="
